#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Mar 31, 2018 11:27:11 PM

import sys
import welcome
import led

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
	from Tkinter import StringVar,END
except ImportError:
	from tkinter import StringVar,END

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import admin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Admin (root)
    admin_support.init(root, top)
    root.mainloop()

w = None
def create_Admin(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Admin (w)
    admin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Admin():
    global w
    w.destroy()
    w = None


class Admin:

    def login(self):
        username=self.userBox.get()
        password=self.pwdBox.get()
        if username=="" or password=="":
            self.resultMessage.configure(bg="red")
            self.result.set("Please fill all the fields")
        else:
            if username=="rvce" and password=="rvce":
                self.resultMessage.configure(bg="green")
                self.result.set("Welcome to Command Center")
                self.welcomeWindow()
            else:
                self.resultMessage.configure(bg="red")
                self.result.set("Invalid Login")

    def clear(self):
        self.userBox.delete(0,END)
        self.pwdBox.delete(0,END)

    def welcomeWindow(self):
        self.master.withdraw()
        root2 = Toplevel(self.master)
        self.welcomeWindow = welcome.welcome(root2)

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {DejaVu Sans} -size 20 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x450+491+150")
        top.title("Admin")
        led.led().ledOn(29)

        self.master = top

        self.Label1 = Label(top)
        self.Label1.place(relx=0.18, rely=0.09, height=69, width=356)
        self.Label1.configure(font=font9)
        self.Label1.configure(text='''Admin Panel''')
        self.Label1.configure(width=356)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.22, rely=0.38, height=19, width=76)
        self.Label2.configure(text='''User-ID :''')
        self.Label2.configure(width=76)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.2, rely=0.47, height=19, width=86)
        self.Label3.configure(text='''Password :''')
        self.Label3.configure(width=86)

        self.userBox = Entry(top)
        self.userBox.place(relx=0.38, rely=0.38,height=21, relwidth=0.31)
        self.userBox.configure(background="white")
        self.userBox.configure(font="TkFixedFont")
        self.userBox.configure(width=186)

        self.pwdBox = Entry(top)
        self.pwdBox.place(relx=0.38, rely=0.47,height=21, relwidth=0.31)
        self.pwdBox.configure(background="white")
        self.pwdBox.configure(font="TkFixedFont")
        self.pwdBox.configure(width=186)
        self.pwdBox.configure(show="*")

        self.loginbtn = Button(top)
        self.loginbtn.place(relx=0.22, rely=0.58, height=27, width=97)
        self.loginbtn.configure(activebackground="#d9d9d9")
        self.loginbtn.configure(text='''Login''')
        self.loginbtn.configure(width=97)
        self.loginbtn.configure(command=self.login)

        self.pwdbtn = Button(top)
        self.pwdbtn.place(relx=0.52, rely=0.58, height=27, width=97)
        self.pwdbtn.configure(activebackground="#d9d9d9")
        self.pwdbtn.configure(text='''Cancel''')
        self.pwdbtn.configure(width=97)
        self.pwdbtn.configure(command=self.clear)

        self.result=StringVar()
        self.result.set("")

        self.resultMessage = Label(top)
        self.resultMessage.place(relx=0.22, rely=0.76, height=59, width=306)
        self.resultMessage.configure(width=306)
        self.resultMessage.configure(textvariable=self.result)






if __name__ == '__main__':
    vp_start_gui()



